CSUM-700 -- Add CSP credits page
csuntechlab/calstatepays pull request #5
Opened 2020-05-04 19:10 UTC by cbenavidesdev

`**READY/HOLD**`
waiting for merge CSUM-706 first

### Migrations
`YES | NO`
no
### What's this PR do?
`What does this pull request achieve? How does it impact the application.`
credit the csp team
### Where should the reviewer start?  
`What piece of the code received the most attention and your reviewer should start by looking at?`

### Steps to Test or Reproduce
`Outline the steps to test or reproduce the PR here.`

example:
```
git pull --prune
git checkout <feature_branch>
bundle; script/server
```

### Impacted Areas in Application
`List general components of the application that this PR will affect:`

2020-05-07 01:04 UTC, luisjg requested changes
See comments

2020-05-07 01:04 UTC, luisjg commented on resources/src/js/router/views/credits/index.vue
> +            src="https://csun-metalab-clouddrive.s3-us-west-2.amazonaws.com/media/faculty/richard.moore/avatar.jpg?2020101345"
You might want to use the media api end point because when he changes that image the numbers will change after the `?`
If you visit
https://api.metalab.csun.edu/media
Scroll down to the section of raw resource retrieval and change steve's name with the professors to see the functionality in action.
https://api.metalab.csun.edu/media/1.1/faculty/media/steven.fitzgerald/avatar?source=true

2020-05-07 17:36 UTC, cbenavidesdev commented on resources/src/js/router/views/credits/index.vue
> +            src="https://csun-metalab-clouddrive.s3-us-west-2.amazonaws.com/media/faculty/richard.moore/avatar.jpg?2020101345"
true!

2020-05-08 05:17 UTC, luisjg requested changes
Use the following URLs, please

Richard Moore:
https://api.metalab.csun.edu/media/1.1/faculty/media/richard.moore/avatar?source=true

Kenneth Chapman:
https://api.metalab.csun.edu/media/1.1/faculty/media/kenneth.chapman/avatar?source=true

2020-05-08 05:40 UTC, cbenavidesdev commented
woops, i copied the wrong link...

2020-05-08 23:35 UTC, luisjg approved these changes

2020-05-09 15:39 UTC, merged